config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper

  mount RailsAdmin::Engine => '/dashboard', as: 'rails_admin'
  mount APINAME::Root => '/apiname'

  resources :parkings

  devise_for :users
  root to: "home#landing"

  get 'home/landing'
  get 'home/welcome'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    if user.has_role? (:MasterAdmin)
      can :manage, :all               # you need it like pre condition
      can :access, :rails_admin       # only allow admin users to access Rails Admin
      can :dashboard                  # allow access to dashboard
    end

    if user.has_role? (:Admin)
      can :access, :rails_admin       # only allow admin users to access Rails Admin
      can :dashboard, :all
      can [:read, :create], BusRoute
      can [:read, :create], Vehicle
      can [:read], Company
      can [:read, :create, :update], AssignedRoute
      can [:read, :create], User
      can [:read], Role
      can [:read], Location
    end

    if user.has_role? (:RegularUser)
      can [:read], :all
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/parking.rb
class Parking < ApplicationRecord
  has_many :users_by_parkings
  has_many :users, through: :users_by_parkings
  belongs_to :owner, :class_name => "User", foreign_key: :user_id

  validates :name, presence: true, uniqueness: { case_sensitive: false }

end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  validates :name, presence: true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :assign_default_role

  has_many :users_by_parkings
  has_many :parkings, through: :users_by_parkings
  has_one :parking

  before_save { email.downcase! }


  validates :name, presence: true,
                    format: { with: /\A\S[a-z ñ A-Z Ñ\s]*\S\z/ }
  validates :last_name, presence: true,
                    format: { with: /\A\S[a-z ñ A-Z Ñ\s]*\S\z/ }
  validates :address, presence: true

  validates :document, presence: true,
                    :numericality => {:only_integer => true},uniqueness: { case_sensitive: false }
  validates :phone, presence: true,
                    :numericality => {:only_integer => true}
  validates :email, presence: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }

  def assign_default_role
    #self.add_role(:RegularUser) if self.roles.blank?
    self.add_role(:RegularUser)
  end
end

app/models/users_by_parking.rb
class UsersByParking < ApplicationRecord
  belongs_to :parking
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:last_name,:document,:address,:email,:document,:phone,:role, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name,:last_name,:document,:address,:email,:document,:phone,:role, :password, :password_confirmation])
    #devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone, :email, bank_attributes: [:bank_name, :bank_account]])
  end

  def after_sign_in_path_for(resource)
    if resource.is_a?(User)
      if resource.has_role? :MasterAdmin
        rails_admin_path
      elsif resource.has_role? :Admin
        #posiblemente a asiganar rutas o a visualizar flota
        #_path
        root_path
      elsif resource.has_role? :RegularUser
        home_welcome_path
      else
        root_path
      end
    else resource.is_a?(Vehicle)
      root_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "application", only: [:welcome]
  layout "layoutvideo", only: [:landing]

  skip_before_action :authenticate_user!, :only => [:landing]
  def landing
  end

  def welcome
  end
end

app/controllers/parkings_controller.rb
class ParkingsController < ApplicationController
  before_action :set_parking, only: [:show, :edit, :update, :destroy]

  # GET /parkings
  # GET /parkings.json
  def index
    @parkings = Parking.all
  end

  # GET /parkings/1
  # GET /parkings/1.json
  def show
  end

  # GET /parkings/new
  def new
    @parking = Parking.new
  end

  # GET /parkings/1/edit
  def edit
  end

  # POST /parkings
  # POST /parkings.json
  def create
    @parking = Parking.new(parking_params)

    respond_to do |format|
      if @parking.save
        format.html { redirect_to @parking, notice: 'Parking was successfully created.' }
        format.json { render :show, status: :created, location: @parking }
      else
        format.html { render :new }
        format.json { render json: @parking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parkings/1
  # PATCH/PUT /parkings/1.json
  def update
    respond_to do |format|
      if @parking.update(parking_params)
        format.html { redirect_to @parking, notice: 'Parking was successfully updated.' }
        format.json { render :show, status: :ok, location: @parking }
      else
        format.html { render :edit }
        format.json { render json: @parking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parkings/1
  # DELETE /parkings/1.json
  def destroy
    @parking.destroy
    respond_to do |format|
      format.html { redirect_to parkings_url, notice: 'Parking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parking
      @parking = Parking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parking_params
      params.require(:parking).permit(:name, :address, :phone, :email, :nit)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/basic_helper.rb
module BasicHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/parkings_helper.rb
module ParkingsHelper
end

app/views/basic/landing.html.erb
<%= modal_toggle 'Modal', dialog: '#modal'%>
<%= modal_dialog :id => "modal",
         :header => { :show_close => true, :title => 'Modal header' },
         :body   => 'This is the body',
         :footer => content_tag(:button, 'Save', :class => 'btn btn-primary')
%>

<div class="container">
    <div class="row">
        <div class='col-sm-6'>
            <div class="form-group">
                <div class='input-group date' id='datetimepicker1'>
                    <input type='text' class="form-control" />
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            $(function () {
                $('#datetimepicker1').datetimepicker();
            });
        </script>
    </div>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/landing.html.erb
<%= render 'partials/newsession' %>
<%= render 'partials/landingbuttons' %>

app/views/home/welcome.html.erb
<h1>Home#welcome</h1>
<p>Find me in app/views/home/welcome.html.erb</p>


<p>Entro al parqueadero como usuario ya logueado</p>

<%= modal_toggle 'Modal', dialog: '#modal'%>
<%= modal_dialog :id => "modal",
         :header => { :show_close => true, :title => 'Modal header' },
         :body   => 'This is the body',
         :footer => content_tag(:button, 'Save', :class => 'btn btn-primary')
%>

<div class="container">
    <div class="row">
        <div class='col-sm-6'>
            <div class="form-group">
                <div class='input-group date' id='datetimepicker1'>
                    <input type='text' class="form-control" />
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            $(function () {
                $('#datetimepicker1').datetimepicker();
            });
        </script>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Parkings" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Parkings</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
            <li>
              <%= link_to destroy_user_session_path, class: 'btn btn-danger col-md-12', :method => :delete do %>
                Salir <%=fa_icon "sign-out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">


          <% unless flash.empty? %>
              <script type="text/javascript">
                <% flash.each do |f| %>
                  <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
                  toastr['<%= type %>']('<%= f[1] %>');
              <% end %>
            </script>
          <% end %>
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>

          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>

            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/layoutvideo.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your application</title>
    <meta name="Description" content="Parqueaderos Montallantas y Lava autos">
    <meta name="Developer" description="Ivan Martinez C">
     <!-- <meta name="turbolinks-cache-control" content="no-cache" >  -->
    <%= csrf_meta_tags %>

    <%= favicon_link_tag 'favicon.ico' %>


    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oxygen:400,300,700">
    <link href="https://fonts.googleapis.com/css?family=Wendy+One|Anton" rel="stylesheet">

    <%= stylesheet_link_tag    'layoutvideo', media: 'all', 'data-turbolinks-track' => true ,'data-turbolinks-track': 'reload' %>
     <!-- Datatable CDN -->
    <%= stylesheet_link_tag 'https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css', media: "all", 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag 'https://cdn.datatables.net/responsive/2.2.0/css/responsive.dataTables.min.css', media: "all", 'data-turbolinks-track': 'reload' %>



    <%= javascript_include_tag 'layoutvideo', 'data-turbolinks-track' => true, 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag "//maps.google.com/maps/api/js?key=AIzaSyC-rTnZeEdXeNX4oIRjP6cj33zregPQPIY" %>
    <%= javascript_include_tag "//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js" %>
    <%= javascript_include_tag "//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>

    <%= javascript_include_tag 'https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js'%>
    <%= javascript_include_tag 'https://cdn.datatables.net/responsive/2.2.0/js/dataTables.responsive.min.js'%>
  </head>
  <body class="margin-bottom-footer">

    <video id="my-video" class="video" muted="" loop="" poster="<%= asset_path("backg1.png")%>" ) %>">
      <source id="video" src="<%= video_path("parkingfull.webm")%>" type="video/webm">
    </video><!-- /video -->
    <% if user_signed_in? %>
      <%= render 'partials/navbar'%>
    <%end%>

    <div class="content " style="margin-bottom: 110px;">



      <% unless flash.empty? %>
        <script type="text/javascript">
          <% flash.each do |f| %>
            <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
            toastr['<%= type %>']('<%= f[1] %>');
          <% end %>
        </script>
      <% end %>

      <%= yield %>

      <footer id="footer" class="navbar-fixed-bottom text-center">
            <p style="color:white; margin-bottom: 0px;">
              Vanmartc Developments 2017 &copy;. All rights reserved &#174;.
            </p>
      </footer>

    </div><!-- /content -->


  </body>
  <script>
  ( function() {
    /**
     * Video element
     * @type {HTMLElement}
     */
    var video = document.getElementById("my-video");

    /**
     * Check if video can play, and play it
     */
    video.addEventListener( "canplay", function() {
      video.play();
    });
  })();

  function GetCookie(name) {
    var arg=name+"=";
    var alen=arg.length;
    var clen=document.cookie.length;
    var i=0;
    while (i<clen) {
        var j=i+alen;

        if (document.cookie.substring(i,j)==arg)
            return "1";
        i=document.cookie.indexOf(" ",i)+1;
        if (i==0)
             break;
     }
    return null;
}

function aceptar_cookies(){
    var expire=new Date();
    expire=new Date(expire.getTime()+86400000);
    document.cookie="cookies_surestao=aceptada; expires="+expire;

    var visit=GetCookie("cookies_surestao");
    if (visit==1){
        popbox3();
    }
}

jQuery(function() {
    var visit=GetCookie("cookies_surestao");
    if (visit==1){
        $('#overbox3').toggle();
    } else {
        var expire=new Date();
        expire=new Date(expire.getTime()+86400000);
        document.cookie="cookies_surestao=aceptada; expires="+expire;
    }
});

function popbox3() {
    $('#overbox3').toggle();
}
  </script>
</html>

app/views/parkings/_form.html.erb
<%= form_for @parking, html: { class: 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :name, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :address, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :phone, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :phone, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :email, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :nit, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :nit, class: 'text_field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, class: 'btn btn-primary' %>
      <%= link_to t('.cancel', default: t("helpers.links.cancel")),
                  parkings_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/parkings/edit.html.erb
<%- model_class = Parking -%>
<div class="page-header">
  <h1><%=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: model_class.model_name.human.titleize %></h1>
</div>
<%= render partial: 'form' %>

app/views/parkings/index.html.erb
<%- model_class = Parking -%>
<div class="page-header">
  <h1><%=t '.title', default: model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:nit) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', default: t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @parkings.each do |parking| %>
      <tr>
        <td><%= parking.id %></td>
          <td><%= parking.name %></td>
          <td><%= parking.address %></td>
          <td><%= parking.phone %></td>
          <td><%= parking.email %></td>
          <td><%= parking.nit %></td>
        <td><%=l parking.created_at, format: :long %></td>
        <td>
          <%= link_to parking_path(parking), class: 'btn btn-xs', title: "#{ t('.show', default: t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
          <%- end -%>
          <%= link_to edit_parking_path(parking), class: 'btn btn-xs', title: "#{ t('.edit', default: t('helpers.links.edit')) }" do %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to parking_path(parking), method: :delete, data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-xs', title: "#{ t('.destroy', default: t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', default: t("helpers.links.new")),
            new_parking_path,
            class: 'btn btn-primary' %>

app/views/parkings/new.html.erb
<%- model_class = Parking -%>
<div class="page-header">
  <h1><%=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human.titleize %></h1>
</div>
<%= render partial: 'form' %>

app/views/parkings/show.html.erb
<%- model_class = Parking -%>
<div class="page-header">
  <h1><%=t '.title', default: model_class.model_name.human.titleize %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @parking.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:address) %></dt>
      <dd><pre class="prettyprint"><%= @parking.address %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:phone) %></dt>
      <dd><pre class="prettyprint"><%= @parking.phone %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:email) %></dt>
      <dd><pre class="prettyprint"><%= @parking.email %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:nit) %></dt>
      <dd><pre class="prettyprint"><%= @parking.nit %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', default: t("helpers.links.back")),
              parkings_path, class: 'btn btn-default'  %>
  <%= link_to t('.edit', default: t("helpers.links.edit")),
              edit_parking_path(@parking), class: 'btn btn-default' %>
  <%= link_to t('.destroy', default: t("helpers.links.destroy")),
              parking_path(@parking),
              method: 'delete',
              data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) },
              class: 'btn btn-danger' %>
</div>

app/views/partials/_landingbuttons.html.erb
<div class="row margin__row">
  <div class="col-md-6 col-xs-12 col-sm-10 col-sm-offset-1 col-md-offset-3">
    <%= link_to new_user_registration_path, class: 'content__wy text-center'  do  %>
       Registrarme <%= fa_icon "pencil"%>
    <%end%>
  </div>
</div>

app/views/partials/_navbar.html.erb
<div class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">YuxiTest</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav navbar-right ">
            <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <i class="fa fa-user" aria-hidden="true"></i>
                  <%= current_user.email %>
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <%= link_to edit_user_registration_path do %>
                      <i class="fa fa-user-plus" aria-hidden="true"></i> Edit User
                    <%end%>
                  </li>
                  <li>
                    <% if user_signed_in? %>
                      <% if current_user.has_any_role? :Admin, :MasterAdmin %>
                        <%= link_to rails_admin_path do %>
                          <i class="fa fa-user-plus" aria-hidden="true"></i> Go to Dashboard
                        <%end%>
                      <%end%>
                    <%end%>
                  </li>
                  <hr>
                  <li>
                    <%= link_to destroy_user_session_path, :method => :delete do %>
                      <i class="fa fa-sign-out" aria-hidden="true"></i> LogOut
                    <%end%>
                  </li>
                </ul>
              </li>
            <%else%>
              <li>
                <%= link_to('Register', new_user_registration_path)  %>
              </li>
              <li>
                <%= link_to('Login', new_user_session_path)  %>
              </li>
            <%end%>
          </ul>
        </div>
      </div>
    </div>

app/views/partials/_newsession.html.erb
  <div class="col-md-6 col-xs-12 col-sm-10 col-sm-offset-1 col-md-offset-3  forms__border">
    <h1 style="color: yellow">Bienvenido</h1>
    <hr>

    <%= form_for('user', url: user_session_path) do |f| %>

    <div class="form-group">
      <%= f.email_field :email, autofocus: true, :class => "form-control", :placeholder => "Enter Email",:required => "required" %>
      <small id="emailHelp" class="form-text text-muted">No compartiremos tu email con alguien más.</small>
    </div>


    <div class="form-group">
      <%= f.password_field :password, autocomplete: "off", :class => 'form-control', :placeholder => "Password",:required => "required" %>
      <small id="emailHelp" class="form-text text-muted">Nunca dibulgues tu contraseña.</small>
    </div>

    <div class="actions">
      <%= button_tag "Edit", :type => "submit", class: "login__button" do %>
        Entrar <%= fa_icon "sign-in"%>
      <%end%>
    </div>

  <% end %>
  </div>